# Generated by Django 5.1.15 on 2026-10-08 06:28

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("root", "Root"),
                            ("dive", "Dive"),
                            ("eli5", "Eli5"),
                            ("example", "Example"),
                            ("define", "Define"),
                            ("ask", "Ask"),
                            ("visual", "Visual"),
                            ("relevance", "Relevance"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("streaming", "Streaming"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("anchor_text", models.TextField(blank=True)),
                ("title", models.TextField(blank=True)),
                ("lens", models.JSONField(blank=True, default=dict)),
                ("lens_bucket", models.CharField(blank=True, max_length=64)),
                ("order", models.IntegerField(default=0)),
                ("depth", models.IntegerField(default=0)),
                ("collapsed", models.BooleanField(default=False)),
                ("reused", models.BooleanField(default=False)),
                (
                    "content_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="content.contentvariant",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="learning.node",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooted_nodes",
                        to="learning.node",
                    ),
                ),
            ],
            options={
                "db_table": "learning_node",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Span",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("start_offset", models.IntegerField(blank=True, null=True)),
                ("end_offset", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spans",
                        to="content.concept",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sourced_spans",
                        to="learning.node",
                    ),
                ),
            ],
            options={
                "db_table": "learning_span",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="span",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nodes",
                to="learning.span",
            ),
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(blank=True)),
                ("lens", models.JSONField(blank=True, default=dict)),
                ("lens_bucket", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "learning_thread",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="span",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spans",
                to="learning.thread",
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("context", models.TextField(blank=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="learning.span",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="learning.thread",
                    ),
                ),
            ],
            options={
                "db_table": "learning_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="node",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="learning.thread",
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["thread", "parent"], name="learning_no_thread__046951_idx"
            ),
        ),
    ]
