# Generated by Django 5.1.15 on 2026-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="gist",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="summary_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="kind",
            field=models.CharField(
                choices=[
                    ("root", "Root"),
                    ("followup", "Followup"),
                    ("dive", "Dive"),
                    ("eli5", "Eli5"),
                    ("example", "Example"),
                    ("define", "Define"),
                    ("ask", "Ask"),
                    ("visual", "Visual"),
                    ("relevance", "Relevance"),
                ],
                max_length=16,
            ),
        ),
    ]
