# Generated by Django 5.1.15 on 2026-10-10 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning",
            "0002_node_gist_thread_summary_thread_summary_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="span",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="learning.span",
            ),
        ),
    ]
