# Generated by Django 5.1.15 on 2026-10-07 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.BigIntegerField(default=0)),
                ("lifetime_granted", models.BigIntegerField(default=0)),
                ("lifetime_spent", models.BigIntegerField(default=0)),
                ("version", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credits_wallet",
            },
        ),
        migrations.CreateModel(
            name="CreditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delta", models.BigIntegerField()),
                ("balance_after", models.BigIntegerField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("debit", "Debit"),
                            ("refund", "Refund"),
                            ("adjust", "Adjust"),
                            ("expire", "Expire"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("signup_grant", "Signup Grant"),
                            ("generation", "Generation"),
                            ("cache_reuse", "Cache Reuse"),
                            ("failed_generation", "Failed Generation"),
                            ("plan_refill", "Plan Refill"),
                            ("purchase", "Purchase"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="credits.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "credits_credit_entry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"],
                        name="credits_cre_wallet__60501b_idx",
                    )
                ],
            },
        ),
    ]
