# Generated by Django 5.1.15 on 2026-10-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0001_initial"),
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditentry",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_entries",
                to="telemetry.requestlog",
            ),
        ),
    ]
