# Generated by Django 5.1.15 on 2026-10-08 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        ("credits", "0002_creditentry_request"),
        ("learning", "0001_initial"),
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(blank=True, max_length=16)),
                ("lens_bucket", models.CharField(blank=True, max_length=64)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "lookup_layer",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("broadened", "Broadened"),
                            ("semantic", "Semantic"),
                            ("generated", "Generated"),
                        ],
                        default="generated",
                        max_length=16,
                    ),
                ),
                ("cost", models.BigIntegerField(default=0)),
                ("tokens_in", models.IntegerField(blank=True, null=True)),
                ("tokens_out", models.IntegerField(blank=True, null=True)),
                ("vendor_cost_micros", models.BigIntegerField(blank=True, null=True)),
                (
                    "price_version",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="content.contentvariant",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="learning.node",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="telemetry.requestlog",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="learning.thread",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="credits.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "credits_usage_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"],
                        name="credits_usa_wallet__6e91f0_idx",
                    ),
                    models.Index(
                        fields=["cache_hit", "kind"],
                        name="credits_usa_cache_h_3cf7cc_idx",
                    ),
                ],
            },
        ),
    ]
