# Generated by Django 5.1.15 on 2026-10-08 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("credits", "0003_usageevent"),
        ("learning", "0001_initial"),
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(blank=True, max_length=16)),
                ("lens_bucket", models.CharField(blank=True, max_length=64)),
                ("context_fingerprint", models.CharField(blank=True, max_length=64)),
                ("prompt_version", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("messages", models.JSONField(blank=True, default=list)),
                ("lens", models.JSONField(blank=True, default=dict)),
                ("cost", models.BigIntegerField(default=0)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "lookup_layer",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("broadened", "Broadened"),
                            ("semantic", "Semantic"),
                            ("generated", "Generated"),
                        ],
                        default="generated",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("streaming", "Streaming"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to="content.concept",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to="learning.node",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to="telemetry.requestlog",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="learning.thread",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="credits.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "generation_generation_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
