# Generated by Django 5.1.15 on 2026-10-07 14:20

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("text", models.TextField()),
                (
                    "kind_hint",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("question", "Question"),
                            ("entity", "Entity"),
                            ("phrase", "Phrase"),
                            ("term", "Term"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_concept",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConceptLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("root", "Root"),
                            ("dive", "Dive"),
                            ("eli5", "Eli5"),
                            ("example", "Example"),
                            ("define", "Define"),
                            ("ask", "Ask"),
                            ("visual", "Visual"),
                            ("relevance", "Relevance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("weight", models.IntegerField(default=1)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="content.concept",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="content.concept",
                    ),
                ),
            ],
            options={
                "db_table": "content_concept_link",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "child", "kind"),
                        name="content_concept_link_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("root", "Root"),
                            ("dive", "Dive"),
                            ("eli5", "Eli5"),
                            ("example", "Example"),
                            ("define", "Define"),
                            ("ask", "Ask"),
                            ("visual", "Visual"),
                            ("relevance", "Relevance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("lens_bucket", models.CharField(max_length=64)),
                (
                    "lens_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "context_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("prompt_version", models.CharField(max_length=32)),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("citations", models.JSONField(blank=True, default=list)),
                ("est_read_seconds", models.IntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="content.concept",
                    ),
                ),
            ],
            options={
                "db_table": "content_content_variant",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["concept", "kind", "lens_bucket"],
                        name="content_con_concept_623e7a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "concept",
                            "kind",
                            "lens_bucket",
                            "context_fingerprint",
                            "prompt_version",
                        ),
                        name="content_variant_unique_lens_context",
                    )
                ],
            },
        ),
    ]
