# Generated by Django 5.1.15 on 2026-10-07 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("credits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("input_per_1k_micros", models.BigIntegerField()),
                ("output_per_1k_micros", models.BigIntegerField()),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("version", models.CharField(max_length=32)),
                ("effective_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "telemetry_model_price",
                "ordering": ["-effective_at"],
                "unique_together": {("model", "version")},
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=64)),
                ("method", models.CharField(default="POST", max_length=8)),
                ("kind", models.CharField(blank=True, max_length=32)),
                ("lens_bucket", models.CharField(blank=True, max_length=64)),
                ("cache_hit", models.BooleanField(blank=True, null=True)),
                (
                    "lookup_layer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exact", "Exact"),
                            ("broadened", "Broadened"),
                            ("semantic", "Semantic"),
                            ("generated", "Generated"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "screening_status",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("block", "Block"),
                            ("review", "Review"),
                        ],
                        default="allow",
                        max_length=16,
                    ),
                ),
                (
                    "screening_category",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("screening_score", models.FloatField(blank=True, null=True)),
                (
                    "screening_provider",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("denied", "Denied"),
                            ("blocked", "Blocked"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("credits_charged", models.BigIntegerField(default=0)),
                ("vendor_cost_micros", models.BigIntegerField(blank=True, null=True)),
                ("tokens_in", models.IntegerField(blank=True, null=True)),
                ("tokens_out", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "price_version",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "client_fingerprint",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="credits.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "telemetry_request_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="telemetry_r_user_id_6a6188_idx",
                    ),
                    models.Index(
                        fields=["kind", "cache_hit"], name="telemetry_r_kind_8f76bf_idx"
                    ),
                ],
            },
        ),
    ]
